sensor:
  host: "10.40.200.32"
  port: 50003  # Port for both sensors
  read_interval: 1.0  # seconds
  timeout: 10  # seconds
  sensors:
    - name: "2m_sensor"
      height: 2
    - name: "24m_sensor"
      height: 24

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
